######################################
# Collection of tasks to configure my desktop.
# Written by: Taylor Ivy
#
# List of reference documentation:
# https://docs.ansible.com/ansible/latest/collections/community/general/flatpak_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html
# https://docs.ansible.com/ansible/latest/collections/community/general/flatpak_remote_module.html
#
# To run: ansible-playbook -e @setup_secrets.enc --ask-vault-pass -K install_setup.yml
######################################

- hosts: localhost
  connection: local
  become_user: root
  become: yes

  collections:
    - community.general.flatpak
    - community.general.flatpak_remote

  tasks:
    - name: Get Fedora Version
      command: "rpm -E %fedora"
      register: fedora_version

    - name: Upgrade all packages
      dnf: 
        name: "*"
        state: latest

    - name: Install RPM Fusion Free
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present

    - name: Install RPM Fusion NonFree
      dnf:
        name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm"
        state: present

    - name: Install Nvidia Driver
      dnf:
        name: akmod-nvidia
        state: latest

    - name: Add the flathub flatpak repo
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install VLC
      dnf:
        name: vlc
        state: present

    - name: Install cifs-utils
      dnf:
        name: cifs-utils
        state: present
    
    - name: Install Cron daemon
      dnf:
        name: cronie
        state: present

    - name: Start Cron service
      systemd:
        name: crond.service
        state: started
        enabled: yes

    - name: Install Discord Flatpak
      community.general.flatpak:
        name: com.discordapp.Discord
        state: present

    - name: Mount 2nd Hard Drive to /etc/fstab
      mount:
        path: /media/library
        src: UUID="{{ ansible_devices.sda.partitions.sda2.uuid }}"
        fstype: ntfs
        state: mounted
        opts: defaults,nls=utf8,umask=000,dmask=027,fmask=137,uid=1000,gid=1000
        dump: '1'
      when: ansible_devices.sda.partitions.sda2 is defined

    - name: Mount Personal Synology NAS
      mount:
        path: /media/personal
        src: "//{{ nas_ip }}/Personal"
        fstype: cifs
        opts: domain=workspace,username={{ nas_user }},password={{ nas_password }},uid=1000,gid=1000
        state: mounted

    - name: Mount Media Synology NAS
      mount:
        path: /media/media
        src: "//{{ nas_ip }}/Media"
        fstype: cifs
        opts: domain=workspace,username={{ nas_user }},password={{ nas_password }},uid=1000,gid=1000
        state: mounted

    - name: Setup Cron for Drive to NAS Sync
      ansible.builtin.cron:
        name: "Sync Drive to NAS"
        minute: "0"
        hour: "1"
        job: "/media/personal/Documents/Technology/Scripts/drive-sync/drive-to-nas-sync.sh"
        user: taylor
        state: present
